[GLOBAL]
pants_version = "2.8.1rc0"
backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.black",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.isort",
	"pants.backend.python.typecheck.mypy"
]

[anonymous-telemetry]
enabled = false

[python]
interpreter_search_paths = ["./.venv/bin/python", "<PYENV>", "<PATH>"]

[test]
extra_env_vars = ["RUN_ENV=test"]