steps:
  # build container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "--build-arg",
        "db_uri=${_DB_URI}",
        "api",
      ]
  # deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_LOCATION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}"
      - "--region"
      - "${_GCR_REGION}"
      - "--platform=managed"

# push image to cloud registry
images: ["${_LOCATION}.gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

substitutions:
  _LOCATION: "asia"
  _GCR_REGION: "asia-east1"
  _SERVICE_NAME: "rc4laundry-api"
  _DB_URI: ""
