version: '3'
services:
  db:
    container_name: rc4laundry-api-db
    image: 'postgres'
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  db-test:
    container_name: rc4laundry-api-test-db
    image: 'postgres'
    ports:
      - $POSTGRES_TEST_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_TEST_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
