version: "3"
services:
  redis_dev:
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/rejson.so

  redis_test:
    image: redislabs/redismod:latest
    ports:
      - 6380:6379
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/rejson.so
