version: "3.2"

services:
  roach_1:
    container_name: roach_1
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - $ROACH_PORT:26257
      - $ROACH_CONSOLE_PORT:8080

  roach_2:
    container_name: roach_2
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - $ROACH_TEST_PORT:26257
      - $ROACH_CONSOLE_TEST_PORT:8080
